spring.application.name=EasyStay

# --- DATABASE H2 ---
spring.datasource.url=jdbc:h2:mem:easystaydb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- JPA & HIBERNATE ---
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- INIZIALIZZAZIONE DATI (Il punto cruciale) ---
# 1. Carica SOLO il file compatibile con H2
spring.sql.init.data-locations=classpath:data-test.sql
# 2. Eseguilo SOLO DOPO che Hibernate ha creato le tabelle
spring.jpa.defer-datasource-initialization=true

# --- LOGGING ---
logging.level.org.springframework.beans.factory=INFO
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %highlight(%-5level) %magenta([T:%X{traceId}]) %cyan([S:%X{sessionId}]) - %msg%n

# --- CONSOLE ---
spring.h2.console.enabled=true

spring.h2.console.settings.web-allow-others=true

spring.datasource.generate-unique-name=false
spring.datasource.name=easystaydb

# Imposta l'URL di default nella schermata di login della console
spring.h2.console.path=/h2-console
