spring.application.name=EasyStay

# --- JWT Configuration ---
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# --- DATABASE H2 ---
spring.datasource.url=jdbc:h2:mem:easystaydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- JPA / HIBERNATE ---
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# SVILUPPO: Abilita show-sql per debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- LOGGING (SVILUPPO) ---
# Livello globale
logging.level.root=INFO

# Tuo codice (DEBUG per vedere tutto)
logging.level.it.easystay=DEBUG

# Hibernate SQL (vedi tutte le query)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Spring (INFO)
logging.level.org.springframework=INFO

# Spring Security (solo se debug auth)
# logging.level.org.springframework.security=DEBUG

# SQL init
logging.level.org.springframework.jdbc.datasource.init=DEBUG

# application-h2.properties (SVILUPPO)
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan([U:%X{userId}]) %green(%logger{36}) - %msg%n

# --- H2 CONSOLE ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- DATABASE INIT ---
spring.sql.init.data-locations=classpath:data-test.sql
spring.jpa.defer-datasource-initialization=true