-- 1. POPOLAMENTO UTENTI
INSERT INTO UTENTI (ID, EMAIL, NOME, PASSWORD, RUOLO)
SELECT X, 'utente' || X || '@esempio.it', 'Nome' || X,
       '$2a$10$t.upuAP7Rh.EGKeD3vLA6.9GycgrldjuxRpIQxBm.94K3iwa0ODjO', 'USER'
FROM SYSTEM_RANGE(1, 1000);

-- 2. POPOLAMENTO CASEVACANZA (Assicurati che l'Entity sia CaseVacanza -> casevacanza)
INSERT INTO CASEVACANZA (ID, NOME, INDIRIZZO, CITTA, PREZZO_NOTTE, VERSION)
SELECT X, 'Villa ' || X, 'Via ' || X, 'Roma', 50.0 + (X % 150), 1
FROM SYSTEM_RANGE(1, 4000);

-- 3. POPOLAMENTO PRENOTAZIONI (Cambiato in plurale come da tua indicazione)
INSERT INTO PRENOTAZIONI (ID, DATA_INIZIO, DATA_FINE, CASA_ID, UTENTE_ID)
SELECT
    X,
    DATEADD('DAY', (X % 365), CURRENT_DATE),
    DATEADD('DAY', (X % 365) + 7, CURRENT_DATE),
    (X % 4000) + 1,
    (X % 1000) + 1
FROM SYSTEM_RANGE(1, 50000);

-- 4. SINCRONIZZAZIONE SEQUENZE (Tutte al plurale)
ALTER TABLE UTENTI ALTER COLUMN ID RESTART WITH (SELECT MAX(ID) + 1 FROM UTENTI);
ALTER TABLE CASEVACANZA ALTER COLUMN ID RESTART WITH (SELECT MAX(ID) + 1 FROM CASEVACANZA);
ALTER TABLE PRENOTAZIONI ALTER COLUMN ID RESTART WITH (SELECT MAX(ID) + 1 FROM PRENOTAZIONI);

-- 5. INDICE PER PRESTAZIONI
CREATE INDEX idx_prenotazione_date ON PRENOTAZIONI(DATA_INIZIO);