-- 1. PULIZIA
DELETE FROM PRENOTAZIONE;
DELETE FROM CASAVACANZA;
DELETE FROM UTENTI;

-- 2. POPOLAMENTO UTENTI
INSERT INTO UTENTI (ID, EMAIL, NOME, PASSWORD, RUOLO)
SELECT X, 'utente' || X || '@esempio.it', 'Nome' || X, 'hash_bcrypt_qui', 'USER'
FROM SYSTEM_RANGE(1, 1000);

-- 3. POPOLAMENTO CASAVACANZA
INSERT INTO CASAVACANZA (ID, NOME, INDIRIZZO, CITTA, PREZZO_NOTTE, VERSION)
SELECT X, 'Villa ' || X, 'Via ' || X, 'Roma', 50.0 + (X % 150), 1
FROM SYSTEM_RANGE(1, 4000);

-- 4. POPOLAMENTO PRENOTAZIONE (Date Variabili)
-- Usiamo X per spostare la data di inizio, così non sono tutte uguali
INSERT INTO PRENOTAZIONE (ID, DATA_INIZIO, DATA_FINE, CASA_ID, UTENTE_ID)
SELECT
    X,
    DATEADD('DAY', (X % 365), CURRENT_DATE), -- Distribuisce le date su un anno
    DATEADD('DAY', (X % 365) + 7, CURRENT_DATE),
    (X % 4000) + 1,
    (X % 1000) + 1
FROM SYSTEM_RANGE(1, 50000);

-- 5. SINCRONIZZAZIONE SEQUENZE
ALTER TABLE UTENTI ALTER COLUMN ID RESTART WITH (SELECT MAX(ID) + 1 FROM UTENTI);
ALTER TABLE CASAVACANZA ALTER COLUMN ID RESTART WITH (SELECT MAX(ID) + 1 FROM CASAVACANZA);
ALTER TABLE PRENOTAZIONE ALTER COLUMN ID RESTART WITH (SELECT MAX(ID) + 1 FROM PRENOTAZIONE);

-- 6. INDICE PER PRESTAZIONI
CREATE INDEX idx_prenotazione_date ON PRENOTAZIONE(DATA_INIZIO);